In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
data = pd.read_csv('spotify.csv',date_parser='Date')

In [4]:
missing_values = data.isnull().sum()

missing_values

Date                         0
Shape of You                 0
Despacito                    7
Something Just Like This    47
HUMBLE.                     84
Unforgettable               91
dtype: int64

In [6]:
data.dropna(inplace=True)

In [7]:
data.head()

,Date,Shape of You,Despacito,Something Just Like This,HUMBLE.,Unforgettable
91,2017-04-07,13042637,6533680.0,9736931.0,8055220.0,317011.0
92,2017-04-08,12815920,6660608.0,9334494.0,7280150.0,308838.0
93,2017-04-09,11291392,5683746.0,8077875.0,6396104.0,756145.0
94,2017-04-10,11819128,5762588.0,8678774.0,7162611.0,954504.0
95,2017-04-11,11736951,5877897.0,8591469.0,7468021.0,953037.0

In [8]:
data.tail()

,Date,Shape of You,Despacito,Something Just Like This,HUMBLE.,Unforgettable
361,2018-01-05,4492978,3450315.0,2408365.0,2685857.0,2869783.0
362,2018-01-06,4416476,3394284.0,2188035.0,2559044.0,2743748.0
363,2018-01-07,4009104,3020789.0,1908129.0,2350985.0,2441045.0
364,2018-01-08,4135505,2755266.0,2023251.0,2523265.0,2622693.0
365,2018-01-09,4168506,2791601.0,2058016.0,2727678.0,2627334.0